/**
 * Marca (como la escribe CADAM o Cars, en mayúsculas) -> archivo en /marcas.
 *
 * GENERADO por un script del scratchpad a partir del dataset público de logos
 * de autos (filippofilip95/car-logos-dataset), más Wikimedia Commons para los
 * que faltaban y nuestros propios assets (JMEV). Si falta una marca, se
 * agrega el PNG a public/marcas y una línea acá.
 *
 * Varias marcas apuntan al mismo archivo a propósito: KGM es SsangYong,
 * BEIJING es BAIC, las tres carrocerías de Iveco son Iveco. Las que no tienen
 * logo caen al monograma (ver logo-marca.tsx); no es un error.
 */
export const LOGOS_MARCA: Record<string, string> = {
  "AGRALE": "agrale",
  "AION": "aion",
  "ARCFOX": "arcfox",
  "AUDI": "audi",
  "AVATR": "avatr",
  "BAIC": "baic-motor",
  "BAOJUN": "baojun",
  "BEIJING": "baic-motor",
  "BESTUNE": "bestune",
  "BMW": "bmw",
  "BRILLIANCE": "brilliance",
  "BUICK": "buick",
  "BYD": "byd",
  "CADILLAC": "cadillac",
  "CDW SINOTRUK": "sinotruk",
  "CHANGAN": "changan",
  "CHERY": "chery",
  "CHEVROLET": "chevrolet",
  "CITROEN": "citroen",
  "DAYUN": "dayun",
  "DFM": "dongfeng",
  "DODGE": "dodge",
  "DONGFENG": "dongfeng",
  "FAW": "faw",
  "FERRARI": "ferrari",
  "FIAT": "fiat",
  "FORD": "ford",
  "FOTON": "foton",
  "FREIGHTLINER": "freightliner",
  "FUSO": "fuso",
  "GAC": "gac-group",
  "GEELY": "geely",
  "GENESIS": "genesis",
  "GMC": "gmc",
  "GREAT WALL": "great-wall",
  "HAIMA": "haima",
  "HAVAL": "haval",
  "HIGER": "higer",
  "HINO": "hino",
  "HONDA": "honda",
  "HYUNDAI": "hyundai",
  "ICAUR": "icaur",
  "ISUZU": "isuzu",
  "IVECO": "iveco",
  "IVECO/COMIL": "iveco",
  "IVECO/MASCARELLO": "iveco",
  "JAC": "jac",
  "JAGUAR": "jaguar",
  "JEEP": "jeep",
  "JETOUR": "jetour",
  "JMC": "jmc",
  "KAIYI": "kaiyi",
  "KARRY": "karry",
  "KG MOBILITY": "ssangyong",
  "KGM": "ssangyong",
  "KGM SSANGYONG": "ssangyong",
  "KIA": "kia",
  "KING LONG": "king-long",
  "KINGLONG": "king-long",
  "LADA": "lada",
  "LAMBORGHINI": "lamborghini",
  "LANCIA": "lancia",
  "LAND ROVER": "land-rover",
  "LEAPMOTOR": "leapmotor",
  "LEXUS": "lexus",
  "LI XIANG": "li-auto",
  "LIFAN": "lifan",
  "LINCOLN": "lincoln",
  "LOTUS": "lotus",
  "LUXGEN": "luxgen",
  "LYNK & CO": "lynk-and-co",
  "LYNK&CO": "lynk-and-co",
  "MAHINDRA": "mahindra",
  "MASERATI": "maserati",
  "MAXUS": "maxus",
  "MAZDA": "mazda",
  "MERCEDES BENZ": "mercedes-benz",
  "MG": "mg",
  "MINI": "mini",
  "MITSUBISHI": "mitsubishi",
  "NISSAN": "nissan",
  "ORA": "ora",
  "PEUGEOT": "peugeot",
  "PORSCHE": "porsche",
  "RADAR": "radar",
  "RAM": "ram",
  "RANDON": "randon",
  "RENAULT": "renault",
  "RIDDARA": "radar",
  "ROX": "rox",
  "SAIC MAXUS": "maxus",
  "SANY": "sany",
  "SCANIA": "scania",
  "SHACMAN": "shacman",
  "SINOTRUK": "sinotruk",
  "SINOTRUK CDW": "sinotruk",
  "SKODA": "skoda",
  "SMART": "smart",
  "SOUEAST": "soueast",
  "SSANGYONG": "ssangyong",
  "SSANYONG": "ssangyong",
  "SUBARU": "subaru",
  "SUZUKI": "suzuki",
  "TANK": "tank",
  "TATA": "tata",
  "TESLA": "tesla",
  "TOYOTA": "toyota",
  "UAZ": "uaz",
  "VOLKSWAGEN": "volkswagen",
  "VOLVO": "volvo",
  "WULING": "wuling",
  "XCMG": "xcmg",
  "XIAOMI": "xiaomi",
  "XPENG": "xpeng",
  "ZEEKR": "zeekr",
  "ZHONGTONG": "zhongtong",
  "ZOTYE": "zotye",
};
